# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e78b283b92c4c00be0f24c21a3dd9a0"
name = "magyx-cart-drawer"
application_url = "https://magyx-cart-drawer-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://magyx-cart-drawer-production.up.railway.app/api/auth" ]
